### ISSUE TITLE
rstudio-server 1.1.383 rstudio initialization error

### ISSUE THREAD

**Issue by robocopAlpha** [randy3k/homebrew-rstudio-server#24]
I was using rstudio-server 1.0.143, and it was working fine. I saw that the brew recipe was moved to this repo and updated to v1.1.383.

However, after installing and following the instructions, when I try to log in (either as my user or root), I get the error message saying 
![screen shot 2018-01-15](https://user-images.githubusercontent.com/35454738/34942343-fcdc681c-f9ff-11e7-980a-92adfda1a744.png)

"rstudio initialization error" 
"Unable to connect to service" or sometimes "Error occurred during transmission".

Any instructions on how to properly install and configure rstudio-server?

**Comment by randy3k** [comment]
It doesn’t sound like an issue of the formula. See if this post could help you. https://stackoverflow.com/questions/24665599/unable-to-start-rstudio-in-centos-getting-error-unable-to-connect-to-service/28385103

**Comment by robocopAlpha** [comment]
After several hours of struggling with the problem, I managed to

**Comment by randy3k** [comment]
I am glad that you have fixed it. Is there any chance that the port was occupied by another instance of rstudio-server?

**Comment by etheleon** [comment]
I'm getting the same error as robocopALpha

**Comment by randy3k** [comment]
My only advice is to make sure all rstudio-server instance has been turn off, then restart it.
